version: '3.9'
networks:
  development:
volumes:
  db_data:
  gem_cache:
services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/var/app:cached
      - gem_cache:/usr/local/bundle/gems
    ports:
      - 3000:3000
    depends_on:
      - db
